[package]
name = "frontier-template-runtime"
version = "0.0.0"
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
edition = "2018"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/substrate-developer-hub/frontier-node-template/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

frame-executive = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
frame-support = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
frame-system = { default-features = false, package = "frame-system", git = "https://github.com/woozzzzy/substrate", branch = "bb" }
frame-system-rpc-runtime-api = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }

pallet-ethereum = { default-features = false, path = "../../frame/ethereum" }
pallet-evm = { default-features = false, path = "../../frame/evm" }
pallet-dynamic-fee = { default-features = false, path = "../../frame/dynamic-fee" }
pallet-evm-precompile-simple = { default-features = false, path = "../../frame/evm/precompile/simple" }
pallet-evm-precompile-sha3fips = { default-features = false, path = "../../frame/evm/precompile/sha3fips" }
pallet-evm-precompile-modexp = { default-features = false, path = "../../frame/evm/precompile/modexp" }
pallet-aura = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-balances = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-grandpa = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-randomness-collective-flip = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-sudo = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-timestamp = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-transaction-payment = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }

sp-api = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-block-builder = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb"}
sp-consensus-aura = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-core = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-inherents = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb"}
sp-io = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-offchain = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-runtime = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-session = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-std = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-transaction-pool = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-version = { default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }

fp-rpc = { default-features = false, path = "../../primitives/rpc" }
fp-self-contained = { default-features = false, path = "../../primitives/self-contained" }

# benchmarking dependencies
frame-benchmarking = { git = "https://github.com/woozzzzy/substrate", branch = "bb", default-features = false, optional = true }
frame-system-benchmarking = { git = "https://github.com/woozzzzy/substrate", branch = "bb", default-features = false, optional = true }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/woozzzzy/substrate", branch = "bb" }

[features]
default = ["std", "aura"]
aura = []
manual-seal = []
std = [
	"codec/std",
	"serde",

	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"fp-rpc/std",
	"fp-self-contained/std",

	"pallet-ethereum/std",
	"pallet-evm/std",
	"pallet-dynamic-fee/std",
	"pallet-evm-precompile-simple/std",
	"pallet-evm-precompile-sha3fips/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-randomness-collective-flip/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",

	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"frame-benchmarking/std",
	"frame-system-benchmarking/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-system-benchmarking",
	"frame-system/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",
]
