[package]
name = "pallet-ethereum"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Ethereum compatibility full block processing emulation pallet for Substrate."
license = "Apache-2.0"
resolver = "2"

[dependencies]
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
frame-system = { version = "4.0.0-dev", default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-balances = { version = "4.0.0-dev", default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-timestamp = { version = "4.0.0-dev", default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-evm = { version = "6.0.0-dev", default-features = false, path = "../evm" }
sp-runtime = { version = "4.0.0-dev", default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-io = { version = "4.0.0-dev", default-features = false, git = "https://github.com/woozzzzy/substrate", branch = "bb" }
fp-evm = { version = "3.0.0-dev", default-features = false, path = "../../primitives/evm" }
evm = { version = "0.30.0", features = ["with-codec"], default-features = false }
ethereum = { version = "0.9.0", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.12", default-features = false }
rlp = { version = "0.5", default-features = false }
sha3 = { version = "0.8", default-features = false }
fp-consensus = { version = "2.0.0-dev", path = "../../primitives/consensus", default-features = false }
fp-rpc = { version = "3.0.0-dev", path = "../../primitives/rpc", default-features = false }
fp-storage = { version = "2.0.0", path = "../../primitives/storage", default-features = false }
fp-self-contained = { version = "1.0.0-dev", path = "../../primitives/self-contained", default-features = false }

[dev-dependencies]
sp-core = { version = "4.0.0-dev", git = "https://github.com/woozzzzy/substrate", branch = "bb" }
libsecp256k1 = { version = "0.5", features = ["static-context", "hmac"] }

[features]
default = ["std"]
std = [
	"serde",
	"rustc-hex/std",
	"codec/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-timestamp/std",
	"pallet-evm/std",
	"sp-io/std",
	"sp-std/std",
	"fp-evm/std",
	"ethereum/std",
	"ethereum-types/std",
	"rlp/std",
	"sha3/std",
	"fp-consensus/std",
	"fp-rpc/std",
	"fp-storage/std",
	"evm/std",
	"fp-self-contained/std",
]
